server:
  port: 9411

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: zipkin-server

management:
  metrics:
    web:
      server:
        auto-time-requests: false