server:
  port: 8769

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: service-zuul

zuul:
  routes:
    user:
      path: /user/**
      serviceId: service-feign
    back:
      path: /back/**
      serviceId: service-feign
